apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718622123130
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: aksautosela.azurecr.io/product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
