apiVersion: apps/v1
kind: Deployment
metadata:
  name: testaks
  labels:
    app: testaks
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718350685701
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testaks
  template:
    metadata:
      labels:
        app: testaks
    spec:
      containers:
        - name: testaks
          image: rgyhhrtyr6yyfh.azurecr.io/image-workflow-1718350685701:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
