apiVersion: apps/v1
kind: Deployment
metadata:
  name: producd
  labels:
    app: producd
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1719905366674
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producd
  template:
    metadata:
      labels:
        app: producd
    spec:
      containers:
        - name: producd
          image: acrsdpdemo.azurecr.io/new-image2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
