apiVersion: apps/v1
kind: Deployment
metadata:
  name: test_deployment
  labels:
    app: testdeployment
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718348071671
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeployment
  template:
    metadata:
      labels:
        app: testdeployment
    spec:
      containers:
        - name: test_deployment
          image: rgyhhrtyr6yyfh.azurecr.io/image-workflow-1718348071671:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
