apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: namespace-workflow-1718622123130
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002