apiVersion: v1
kind: Service
metadata:
  name: testaks
  namespace: namespace-workflow-1718350685701
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: testaks
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002