apiVersion: v1
kind: Service
metadata:
  name: test_deployment
  namespace: namespace-workflow-1718348071671
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: test_deployment
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002