apiVersion: v1
kind: Service
metadata:
  name: producd
  namespace: namespace-workflow-1719905366674
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: producd
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002